USE [master]
GO

/****** Object:  Database [MartynenkoDB]    Script Date: 14.11.2018 16:10:15 ******/
CREATE DATABASE [MartynenkoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MartynenkoDB', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MartynenkoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'MartynenkoDB_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MartynenkoDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MartynenkoDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MartynenkoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MartynenkoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MartynenkoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MartynenkoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MartynenkoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MartynenkoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MartynenkoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MartynenkoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MartynenkoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MartynenkoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MartynenkoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MartynenkoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MartynenkoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MartynenkoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MartynenkoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MartynenkoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MartynenkoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MartynenkoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MartynenkoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MartynenkoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MartynenkoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MartynenkoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MartynenkoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MartynenkoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MartynenkoDB] SET  MULTI_USER 
GO

ALTER DATABASE [MartynenkoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MartynenkoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MartynenkoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MartynenkoDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MartynenkoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MartynenkoDB] SET QUERY_STORE = OFF
GO

USE [MartynenkoDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MartynenkoDB] SET  READ_WRITE 
GO

USE [MartynenkoDB]
GO

/****** Object:  Table [dbo].[Category1]    Script Date: 14.11.2018 16:12:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Category1](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Category1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [MartynenkoDB]
GO

/****** Object:  Table [dbo].[Product]    Script Date: 14.11.2018 16:13:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Category_Id] [int] NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Product] FOREIGN KEY([Category_Id])
REFERENCES [dbo].[Category1] ([Id])
GO

ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Product]
GO

